---
PreCommit:
  BuildizerVerify:
    enabled: true
    required: true
    desc: Verify Buildizer conf file
  BuildizerCiVerify:
    enabled: true
    required: true
    desc: Verify travis configuration is up to date
